stages:
  - name: binary
    if: tag IS present

jobs:
  include:
    - stage: binary
      os: linux
      services:
        - docker

      before_install:
        - docker pull mattipaksula/gem2exe
      script:
        - mkdir releases
        - docker run --name gem2exe -it --volume $(pwd):/gem mattipaksula/gem2exe local --path /gem --out /tmp/gbuild gbuild
        - docker cp gem2exe:/tmp/gbuild releases/gbuild-linux-amd64-${TRAVIS_TAG}

    - stage: binary
      os: osx
      sudo: required
      rvm:
        - "2.6"
      before_install:
        - curl -L https://github.com/matti/gem2exe/releases/download/v0.3.2/gem2exe-darwin-amd64-v0.3.2.gz | gunzip - > gem2exe
        - chmod a+x gem2exe
        - sudo mv gem2exe /usr/local/bin/gem2exe
        - gem2exe setup
      script:
        - mkdir releases
        - gem2exe local --out releases/gbuild-darwin-amd64-${TRAVIS_TAG} gbuild

deploy:
  - provider: releases
    api_key:
      secure: "hyEEUXhX1x+ZPWmSEn9GGjHaGOo0EmRuryyDAUL1BU+S4vBqWULp+dt1G5yTShpER5BuF8UTgwWeSrQs/SOyzSQjqzi5dGss3JMQgagf/ULakbiq+tnZ6x/teKqt5EcGZH9ig9ORmiNrZgmSDEUWmOmRNOI5StzqK4DuQWBv9MKnHDm7klRB/iKLl1B7dy/7z14w6pFBEwrk8GCOtihcJLjztgJVAlM7EMwL9ffziKQhkUthDujKrjCFADRKiPxSmtjHR9he7oO2G/t31/4H/fU4qYS+QutxXVjqHwZjS+WnPYDsZviE0Lqgxi47+TN/62k162nnso9Rz58UgCEPwXny3kzDjfhjXTZcw8qH9TRSQmG1XjIzzhXFj4ZJ4AGHYOn80gEPhEd5OBHUoDGMkOZhmjg0fQxWo+wAhGj7pvbZtbphpBZwXPK2LVo7klgKigUsYeRC7p8aC/rzbaIXGtsjkM08ZECA1bPST4CWoNJMnNege8aN3B1pjQY1LttkT19KfufraiuJiMEl+alwO6L1zDA6u0nCmRAn+WI/NfPDcH0wpbDX412S5RFnaT+SWiQZ1p+lNzFl0ttr8nNS0abSZAG1qkaJwt/9dT6TgtHwNOI8OH5tpLW6Odmbqb33QSrnw0UHC7W8dCAfR46RBrihyZYDCCT//1AB54FIyVY="
    file_glob: true
    file: releases/*
    skip_cleanup: true
    on:
      tags: true
  - provider: rubygems
    api_key:
      secure: "MB7FiD69ewehaMEwMIr5nqzAE9VGMwk6zq2ZPZkGrm6XS2Ynu5wLZ3v0ahuEvbv9hIyjkVJjYluUncjPECJFQvC1Hl9sP3qju9hUnGqKhcgNXg6GQWGw9XVwiv7ggTaNP0H+F7jq4DkKxljWbkq5Nsy3bi0MridJCGSDiZDj1S4dRZfCh5NiVnPhhUsLDbXzs814IallJou3KlcNVy3zFnEfHpXr3Qxr348BVbzzRDRZ7oEiESGsEzzeGFMKOAPOnazrwsEp3YFWO+/TqhYNAbmHosJQ31W/1/kUSWMcOYtPlkr6tSIlR4jlxB7C1z1TrhZpkxbeBXwIvndeakJwBuWYvTD1wpU0ZM02Cm68cSAKmzvq1zgM3ObGJcLHFOkAIRWdQsQmBdkBhXafP78vROJYJ/jiJ3KAPIJPzTp2lzD5qJhSFPAWFz1fCpDjo0mdRWF1shfQ3/u6k8paCE1PFGxZYsMUC9Q9Q5634+t5YGTSo83rYKf6DyOssQT7oMT9v4MG81zWZCT9MhT3EP6sq1+pRUO9InhAKL6X1yhQYo65faiAbN8REaNdDU0D+RCvdXslFyJCYr+eM6jdvThyYDHRV9J4dfKDpxtT///wXHVlDOBkUIzsk9flv6wmvbuHVgCX2Sp0H1SoLqYJc6BbRFSSBuhZdF52Bo1SRc4RWLQ="
    on:
      branch: master
